# Generated by Django 4.2.4 on 2023-09-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_creation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
